### ISSUE TITLE
feat : user authentication to services

### ISSUE THREAD

**Issue by SantiagoGaonaC** [CIE-UPB/users-control#1]
# Task:

- [x] **Keycloak**:

  - [x] Create roles (*empresario* - *admin*)
  - [x] Add users for testing
  - [x] add credentials
  - [ ] Backup auto for the master/cie **REALMS**

- [ ] **Keycloak & OAuth2-Proxy**:

  - [x] Config oauth2-proxy for clientID
  - [ ] Create routes for logout frontend & backend

- [ ] **Nginx:**

  - [x] Create SSL/HTTPS for localhost

  - [ ] Testing in server using SSL

    **create locations:**

    - [x] auth
    - [x] oauth
    - [x] oauth2/auth
    - [ ] signout
    - [x] "/" master
    - [ ] routes for endpoints `auth_request`
    - [ ] routes for frontend `auth_request`
